version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - aws s3 cp s3://$AUTH_PATH k1te-serverless-test/auth.json
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - cd k1te-serverless-stack-cdktf
      - npm ci
  build:
    commands:
      - echo "CDKTF is synthesizing source code"
      - npm run synth
      - cd cdktf.out/stacks/$STACK
      - terraform init -reconfigure
      - echo "Drift check"
      - terraform plan -detailed-exitcode -refresh=false || EXITCODE=$?
  post_build:
    commands:
      - echo $EXITCODE
      - |
        if [ $EXITCODE -eq 2 ]; then
          echo Drift is detected, event is published
          aws events put-events --entries $EVENT
        fi
cache:
  paths:
    - '/k1te-serverless-stack-cdktf/node_modules/*'

